User.create(name: "Ruby Weiner")
User.create(name: "Andres Manco")
User.create(name: "Juan Simosa")
User.create(name: "Fernando Perez")
User.create(name: "Michael Ortega")
User.create(name: "Mariana Larez")
User.create(name: "Yeri Sanchez")
User.create(name: "Jose Arocha")
User.create(name: "Christian Martinez")
User.create(name: "Emma Sargeant")
User.create(name: "Gaby Ortiz")
User.create(name: "Genesis Pacocano")
user1 = User.create(name: "User1")
user2 = User.create(name: "User2")
user3 = User.create(name: "User3")
user4 = User.create(name: "User4")
user5 = User.create(name: "User5")
User.create(name: "User6")
User.create(name: "User7")
User.create(name: "User8")

Artist.create(name: "Avicii")
Artist.create(name: "Steve Aoki")
Artist.create(name: "Tiesto")
Artist.create(name: "David Guetta")
Artist.create(name: "Martin Garrix")
artist1 = Artist.create(name: "Artist1")
artist2 = Artist.create(name: "Artist2")
artist3 = Artist.create(name: "Artist3")
artist4 = Artist.create(name: "Artist4")
